services:
  - type: web
    name: hair-studio-blessed
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/run_waitress.py"
    envVars:
      - key: PORT
        value: 8000

